### ISSUE TITLE
Class "WireUiComponent" not found

### ISSUE THREAD

**Issue by rafitio** [shopperlabs/framework#130]
Hi, I got error message Class "WireUiComponent" not found when accessing `/login` page.
<img width="1185" alt="Screen Shot 2022-05-23 at 16 34 31" src="https://user-images.githubusercontent.com/26764936/169790292-fa7725d5-f78e-4a36-86ca-68533594b058.png">
.

**Comment by AkramZerarka** [comment]
Just replace WireUiComponent with WireUi
