### ISSUE TITLE
Trix editor Flickering 

### ISSUE THREAD

**Issue by stevebrainng** [shopperlabs/framework#144]
When trix-editor is active on a page it keeps flickering and changes focus to the trix-editor textarea input and thereby you can update other inputs on the page.  a typical example is the **about textarea** at the  `general settings page` 

[Link to Vimeo video for reference](https://vimeo.com/728160197)

**Comment by mckenziearts** [comment]
Update to the last version and reload shopper assets.
Remove your shopper symbolic folder in public and run `php artisan shopper:link` again

**Comment by stevebrainng** [comment]
How do we Update the Documentation to include some of this detailed information? I would gladly send sometime.
