### ISSUE TITLE
Misssing Livewire Component

### ISSUE THREAD

**Issue by stevebrainng** [shopperlabs/framework#145]
A livewire component is missing at the **Related product** tab in **Edit product** page. 
The error Popup when the **Add New Product** button is clicked. 

![image](https://user-images.githubusercontent.com/24863248/178036706-c5d82c52-bb6c-4e74-8652-297b8b2e9888.png)

**Comment by mckenziearts** [comment]
Update to the last version and republish the `shopper/components.php` config file

**Comment by stevebrainng** [comment]
> Update to the last version and republish the `shopper/components.php` config file

Please I sent you a private message on Twitter, is that a convenient place to send it?
