### ISSUE TITLE
Disk [uploads] does not have a configured driver.

### ISSUE THREAD

**Issue by MarkWasfy00** [shopperlabs/framework#147]
i get this errors after trying setup the store 
![Screenshot 2022-08-01 054028](https://user-images.githubusercontent.com/76422492/182067799-ad712d81-08d9-42aa-9045-1cf13d158db8.png)

**Comment by mckenziearts** [comment]
You have to add this lines to your `config/filesystems.php` https://laravelshopper.dev/configuration#update-configurations

**Comment by MarkWasfy00** [comment]
Great it works now , love it so far

**Comment by howdu** [comment]
@mckenziearts if this is a requirement could it be included in the install? Or at a check that it has been configured. Happy to submit PR for this if you agree.
