### ISSUE TITLE
Add product error

### ISSUE THREAD

**Issue by hieuna** [shopperlabs/framework#153]
Hi,
I create product but error: Attempt to read property "id" on null
How can fix it?

**Comment by secrethash** [comment]
I faced the same issue. After looking into the code I found out it was mainly due to no locations were added. You can add a locations from the settings page and then this error will be gone.

**Comment by secrethash** [comment]
I think this is being caused due to wrong operator usage here:
 https://github.com/shopperlabs/framework/blob/c9c0e4e05fcdff8f01b5cd4185b134fbffe3ee75/resources/views/livewire/products/create.blade.php#L131

It is:

```php
@if($inventories->count() <= 1)
```

When it should be:

```php
@if($inventories->count() >= 1)
```

**Comment by hieuna** [comment]
Hi,
@secrethash Thanks for help.
I want to ask one more question. How to edit code that must be edited directly in vendor.
Example: If I want to add any input box in module product. I don't want to go to the vendor to fix it, because it affects the author's next update.
Please guide me if possible. Thanks.

**Comment by thearyanahmed** [comment]
@hieuna One method could be to publish the vendor's assets ( blade files in this case ) and override them. 
That way, when the next update is released, you can simply remove your vendor file and it will work just like before.

**Comment by hieuna** [comment]
@thearyanahmed Thanks for anwser me.
If I delete the edited files, my custom will be lost. I mean is there a way to update to the new version and still keep the things that have been modified? Does this sound difficult?

**Comment by thearyanahmed** [comment]
Well, you just need to change one line, the solution given by secrethash. So, when the next update comes and this issue is fixed by the vendor, you will no longer need your custom file. 

If you still need to keep your custom file, then just don't delete it. Laravel will override the vendor's file with yours. 

If you need both, like some portion of the newly released file and some of your custom code, i don't believe there is a simple way, not that I know of!

**Comment by secrethash** [comment]
@hieuna there is a `shopper:publish` command available. To publish the shopper files.

```sh
php artisan shopper:publish
```

For changes I think @thearyanahmed explained it.

**Comment by hieuna** [comment]
Hi @secrethash , @thearyanahmed Thanks for support me.
