### ISSUE TITLE
Doesn't work install package on Laravel Fresh Install

### ISSUE THREAD

**Issue by widiu7omo** [shopperlabs/framework#154]
### Error
I got an error after installing the framework package. 

Here's the error

![Screen Shot 2022-10-06 at 12 02 36](https://user-images.githubusercontent.com/25941348/194211305-1f49deca-82d8-4201-a352-b395daa39067.png)

### Reproduce Error
First command
`composer create-project --prefer-dist laravel/laravel  my-market`

Second command
`composer require shopper/framework` 

### Env
PHP 8.1
Laravel v9.3.8
Mac OS 12.5.1

**Comment by kevin700523** [comment]
same here

**Comment by kevin700523** [comment]
I got similar error on Laravel 9, it because of the simple-cache dependency, try to specify the psr/simple-cache version as ^2.0 in your composer.json

composer require psr/simple-cache:^2.0 maatwebsite/excel

**Comment by widiu7omo** [comment]
@kevin700523 , Thanks, it's working. It could be alternate for now.
