### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by deecodefuse** [shopperlabs/framework#160]
![image](https://user-images.githubusercontent.com/127820898/231356128-a2d2298d-91a5-4b81-b9e7-6d390fcc7379.png)
[](url)

**Comment by surya0710** [comment]
Did you find any solution to this error?

**Comment by roomdada** [comment]
I have the same problem and need help.

**Comment by mckenziearts** [comment]
Fixed. Please update to the latest release. Thks
