### ISSUE TITLE
Unable to locate a class or view for component [shopper::forms.color-picker].

### ISSUE THREAD

**Issue by errahmouniabdelhamid** [shopperlabs/framework#161]
i have created an attribute of type checkbox and when i want to edit its value i get this error

![Screenshot 2023-04-12 150657](https://user-images.githubusercontent.com/87318869/231500989-2986bc1b-8d28-41ee-ab2c-958c4b728ae4.png)

**Comment by mckenziearts** [comment]
Upgrade to the latest version, this issue is fix
