### ISSUE TITLE
laravelshopper.io domain expired

### ISSUE THREAD

**Issue by joelvh** [shopperlabs/framework#220]
@mckenziearts your laravelshopper.io domain expired about 2 weeks ago. Just making sure you're aware. The website is not viewable there, but laravelshopper.dev seems to work.

**Comment by mckenziearts** [comment]
Hello @joelvh  and thank you for your attention. But I voluntarily shoutdown this domain to keep only the .dev. I prefer to have all the site and documentation on the same domain, it's easier to manage.

**Comment by joelvh** [comment]
ok @mckenziearts - just know that you are still linking to the old domain from your GitHub [repo description and README](https://github.com/shopperlabs/shopper), [org](https://github.com/shopperlabs) and the contact email has the old domain. Those are just examples, but there are more, possibly in the docs.
