### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by basescam** [shopperlabs/framework#224]
When I try to install on pure Laravel 10x, the following error appears:
![image](https://github.com/shopperlabs/shopper/assets/25525095/974418bc-3394-4029-a921-c3514bf8f664)
I use PHP 8.2, MariaDB 10.6.12

**Comment by Kalpeshk9967016292** [comment]
Try commenting line 45
// $table->index(['reference_type', 'reference_id']);
in
2020_00_02_000002_create_inventories_table.php

**Comment by mrbric23** [comment]
![image](https://github.com/shopperlabs/shopper/assets/127897286/b5f1713b-aef8-4f0b-8800-b0c27fcb52ac)

**Comment by mrbric23** [comment]
![image](https://github.com/shopperlabs/shopper/assets/127897286/0d37d32e-16cd-4a4c-a805-b3fcc039da5c)

**Comment by basescam** [comment]
> ![изображение](https://user-images.githubusercontent.com/127897286/274260545-0d37d32e-16cd-4a4c-a805-b3fcc039da5c.png)
> 
> ![изображение](https://user-images.githubusercontent.com/127897286/274260685-6419d65d-c540-455e-87c6-92b528e6c56c.png)

Change the Laravel project root composer.json file to look like this:
```
"minimum-stability": "dev",
"prefer-stable": true
```

**Comment by mrbric23** [comment]
![image](https://github.com/shopperlabs/shopper/assets/127897286/92a25dc2-595a-4b4e-bd4e-a5c46ef494d5)

doesn't work

**Comment by Kalpeshk9967016292** [comment]
Can you share your whole composer.json

**Comment by Kalpeshk9967016292** [comment]
it should look like this

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "shopper/framework": "^2.0@beta"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by mrbric23** [comment]
> Can you share your whole composer.json

YES 

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "lunarphp/lunar": "^0.6.1"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

**Comment by basescam** [comment]
> ![image](https://user-images.githubusercontent.com/127897286/274889817-92a25dc2-595a-4b4e-bd4e-a5c46ef494d5.png)
> 
> doesn't work

Here's my variant of installing Shopper on Laravel 10.x:

```
composer create-project laravel/laravel my-app
php artisan config:clear

```
Next, in the **composer.json** file of the Laravel project, change the **minimum-stability** from "stable" to "dev".

Next, execute the commands:
```
composer require shopper/framework --with-all-dependencies
composer update
```
Next make sure to create a new database and add your database credentials to your **.env** file, you will also want to add your application URL in the **APP_URL** variable.

Next, navigate to the file /vendor/shopper/core/database/migrations/2020_00_02_000002_create_inventories_table.php and replace its contents with the following code:

```php
<?php

declare(strict_types=1);

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Shopper\Core\Helpers\Migration;

return new class() extends Migration
{
    public function up(): void
    {
        Schema::create($this->getTableName('inventories'), function (Blueprint $table): void {
            $this->addCommonFields($table);

            $table->string('name');
            $table->string('code')->unique();
            $table->text('description')->nullable();
            $table->string('email')->unique();
            $table->string('street_address');
            $table->string('street_address_plus')->nullable();
            $table->string('zipcode');
            $table->string('city');
            $table->string('phone_number')->nullable();
            $table->integer('priority')->default(0);
            $table->decimal('latitude', 10, 5)->nullable();
            $table->decimal('longitude', 10, 5)->nullable();
            $table->boolean('is_default')->default(false);

            $this->addForeignKey($table, 'country_id', $this->getTableName('system_countries'));
        });

        Schema::create($this->getTableName('inventory_histories'), function (Blueprint $table): void {
        	$this->addCommonFields($table);

        	$table->morphs('stockable');
        	$table->nullableMorphs('reference');
        	$table->integer('quantity');
        	$table->integer('old_quantity')->default(0);
        	$table->string('event', 75)->nullable();
        	$table->text('description')->nullable();

        	$this->addForeignKey($table, 'inventory_id', $this->getTableName('inventories'), false);
        	$this->addForeignKey($table, 'user_id', $this->getTableName('users'), false);

        	if (Schema::hasTable($this->getTableName('inventory_histories')) && !Schema::hasIndex($this->getTableName('inventory_histories'), 'inventory_histories_reference_type_reference_id_index')) {
        		$table->index(['reference_type', 'reference_id']);
        	}
        });

    }

    public function down(): void
    {
        Schema::dropIfExists($this->getTableName('inventory_histories'));
        Schema::dropIfExists($this->getTableName('inventories'));
    }
};

```
Next we execute the command:
`php artisan shopper:install`

**After this, the installation will be successful, without any errors.**

Now, you need to update the `app/Models/User.php` file. However, if you follow the instructions in the documentation, you will encounter an error and might end up quite frustrated. Shopper changed the namespace names but failed to mention this in their documentation. So, replace 
`use Shopper\Framework\Models\User\User as Authenticatable;` 
with 
`use Shopper\Core\Models\User as Authenticatable;`.
After this, you can smoothly run the command:
`php artisan shopper:admin`
And set up an administrator.

Note that the admin panel URL has also been changed and is not mentioned in the documentation. So, after creating the administrator, to access the control panel, you need to go to:
`example.com/cpanel`

If you follow my instructions, you should be able to seamlessly install and configure Shopper.
I hope my answer helps you.
