### ISSUE TITLE
MIgrations fail on install

### ISSUE THREAD

**Issue by agustinzamar** [shopperlabs/framework#226]
Install shopper in a clean Laravel 10 project

1. composer require shopper/framework --with-dependencies
2. php artisan shopper:install

The issue: 

<img width="1464" alt="image" src="https://github.com/shopperlabs/shopper/assets/36794905/1bae9b96-7d01-4a5c-8ffe-91a128e4a424">

**Comment by basescam** [comment]
A workaround is described here: #224
