### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by vitalijalbu** [shopperlabs/framework#260]
<img width="709" alt="Screenshot 2024-05-04 alle 14 38 30" src="https://github.com/shopperlabs/shopper/assets/40239902/69dd488c-c074-48f3-9d85-4412a01ba1f7">

**Comment by amirmrt** [comment]
https://github.com/abdelhamiderrahmouni/shopper-framework

**Comment by mckenziearts** [comment]
Fix
