### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by 3ollnai** [shopperlabs/framework#263]
![Capture d'écran 2024-06-25 022302](https://github.com/shopperlabs/shopper/assets/77481783/1fb9a6be-ec5f-43da-8231-07ee57588173)

**Comment by mckenziearts** [comment]
Which version of Shopper ?

**Comment by 3ollnai** [comment]
The last one

Le jeu. 18 juill. 2024 à 06:43, Arthur Monney ***@***.***> a
écrit :

**Comment by mckenziearts** [comment]
What version of mysql are you using? Because the require version is 8

**Comment by Shiiza009** [comment]
I had the same exact issue, uninstalled XAMPP as it was using MariaDB V.10, installed mysql from dev.mysql and yup, worked now.
