### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by chapdel** [shopperlabs/framework#45]
Error while installing on fresh laravel project

php version: 8.0.x
laravel version: 8.5.x

![Screenshot from 2021-07-07 23-00-58](https://user-images.githubusercontent.com/20987014/125002084-1175c800-e04c-11eb-8641-7b79e3d15075.png)

**Comment by mckenziearts** [comment]
Try to clear your config by type `php artisan config:clear` and relaunch command

**Comment by afbora** [comment]
I've reproduce same issue on same steps `php artisan shopper:install` and `php artisan config:clear`.

**Comment by chapdel** [comment]
I still have the same problem
