### ISSUE TITLE
Base use of the MailEclipse package

### ISSUE THREAD

**Issue by ReeceM** [shopperlabs/framework#46]
Hi there guys,

So I see that about the last 4 months you used the source for the [MailEclipse](https://github.com/Qoraiche/laravel-mail-editor) package in the framework, I know this as it uses my package that allows the actual thing to function :) Which is totally cool that others are using it.

I totally understand that we all make use of others code, but I do acknowledge the source of my code if I have to make use of someone else's source code.  I am sure Yassine would agree on this. (A point in case is that of a similar situation of the [canvas](https://github.com/austintoddj/canvas#credits) editor using the same code as themsaid's code and not initially crediting him for the base code)

I do think that it would be the nice thing to do is acknowledge in the head of the actual files that use the same source code, not much was changed, so it wasn't new code. I do know and see that some was adjusted for the use with the Livewire stack. But you more than likely could have overridden the UI and extended. (Or opened an issue and I could have helped 😃)

It would be great again if you could at least acknowledge the source of that code as it would mean that the framework does actually become questionable as to how much more is used. 

Please understand that this is meant in the best way possible to keep respect in the open source community as I know that everyone put's quite a bit of time in maintaining packages.

/cc @Qoraiche

**Comment by mckenziearts** [comment]
Hello,
Nice to read your post and I totally agree with what you said 😄. If I have to add a mention in addition to the one put on the interface I will do it you just have to tell me for example what to report.

![Untitled](https://user-images.githubusercontent.com/14105989/125430210-3049a33c-cf30-47c6-a7a2-7e442bce752c.jpg)

**Comment by ReeceM** [comment]
Hello Arthur, thank you for getting back and also handling it in a decent way 😄 

I think @Qoraiche would also be of good input on that and that on the UI is very decent addition. I think it would also be practical to also include that notice in the `Mailables` traits in the framework repo, in that way it still retains acknowledgement too.

--- 

On a separate not, but related. Was there a reason for not including the package into the required ones and just rewrite the UI end part? Was it due to the lack of extendability of the package?

**Comment by mckenziearts** [comment]
Ok I will also add that in the source code. The package itself is great I already use it on several projects but for the sake of UI and customization I didn't want to copy everything and I also wanted to be able to add e-commerce email templates only and not have everything. It is still in development mode. Being an e-commerce solution I wanted to make it a little more suitable.

But if there are any implementation ideas, I am all yes. I put it open source precisely to have the feedback and modify before making an official newsletter to announce the package

**Comment by Qoraiche** [comment]
That's awesome 👏, thanks @mckenziearts, @ReeceM

**Comment by ReeceM** [comment]
> Ok I will also add that in the source code. The package itself is great I already use it on several projects but for the sake of UI and customization I didn't want to copy everything and I also wanted to be able to add e-commerce email templates only and not have everything. It is still in development mode. Being an e-commerce solution I wanted to make it a little more suitable.
> 
> But if there are any implementation ideas, I am all yes. I put it open source precisely to have the feedback and modify before making an official newsletter to announce the package

@mckenziearts thank you for the adding the acknowledgements, and also for making the package open source, it does look very good and nicely put together. 💯 😃 

I think the feedback from you might help us also improve the MailEclipse package to make it a little more extendable for users too 👍
