### ISSUE TITLE
not able to login the backend system 

### ISSUE THREAD

**Issue by codesharpdev** [shopperlabs/framework#57]
Hi Arthur, 

I like the Laravel shopper 2 and installed the framework successfully today. I'm not able to login the backend system 

after installation setup, I have followed the commands, while creating admin user through artisan i have got an error 

`Call to undefined method App\Models\User::assignRole()`

Please help..

<img width="683" alt="Screenshot 2021-07-30 at 3 55 29 PM" src="https://user-images.githubusercontent.com/5584190/127639853-05c8a853-4260-417a-a9b4-30496e053b75.png">

**Comment by mckenziearts** [comment]
Here the solution in the doc https://docs.laravelshopper.io/docs/installation#update-existing-files

Before run the `php artisan shopper:admin` you have to update your User model like this

```php
<?php

use Shopper\Framework\Models\User\User as Authenticatable; 

class User extends Authenticatable
{
    // ...
}
```

**Comment by codesharpdev** [comment]
@mckenziearts thanks, its working fine now, how i can develop front-end theme, can you please provide documentation.
