### ISSUE TITLE
Call to a member function hasRole() on null

### ISSUE THREAD

**Issue by caredev** [shopperlabs/framework#59]
Just after installing on a brand new Laravel project following the steps in the documentation I get a 500 error.

[Wed Aug 04 00:58:05.056772 2021] [php:notice] [pid 1119] [client 192.168.1.231:61838] PHP Fatal error:  Uncaught Error: Call to a member function hasRole() on null in /var/www/laravelshopper/vendor/shopper/framework/src/Exceptions/ShopperExceptionHandler.php:36\nStack trace:\n#0 /var/www/laravelshopper/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Shopper\\Framework\\Exceptions\\ShopperExceptionHandler->render()\n#1 /var/www/laravelshopper/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#3 {main}\n  thrown in /var/www/laravelshopper/vendor/shopper/framework/src/Exceptions/ShopperExceptionHandler.php on line 36

**Comment by mckenziearts** [comment]
Issue already fix. Refer https://docs.laravelshopper.io/docs/installation

**Comment by caredev** [comment]
It is not fixed since I followed exactly the steps on that guide, one by one, copy/paste.
