### ISSUE TITLE
I can't add product

### ISSUE THREAD

**Issue by sayasuhendra** [shopperlabs/framework#60]
![image](https://user-images.githubusercontent.com/4870292/129070945-0beb43cf-53de-478a-a8c4-98f76aa3f2b0.png)

when I click add product always got error 

Attempt to read property "id" on null (View:  /resources/views/vendor/shopper/livewire/products/create.blade.php)

You don't have permission/authorization to access requested page.

![image](https://user-images.githubusercontent.com/4870292/129072369-b516dad2-eeff-4b78-821a-3c4bbe3c03d4.png)

**Comment by mckenziearts** [comment]
To fix it you have to create an inventory and set as default
