### ISSUE TITLE
Save button keeps rolling

### ISSUE THREAD

**Issue by manishlok** [shopperlabs/framework#62]
Hi, thank you for this package.
I am getting an error. When we create any stuff like product, brand, or category, etc. It is being created but the Save button keeps rolling infinitely.  Product is also stored in database. The error is
`[14:51:45] LOG.error: Typed property Shopper\Framework\Http\Livewire\Products\Create::$quantity must not be accessed before initialization {"userId":1,"exception":{}}`
Could you please reply on how to fix this error?
Thank you in advance.

**Comment by mckenziearts** [comment]
Yes I will fix it tomorrow thanks.

**Comment by mckenziearts** [comment]
Fixed. More details here https://github.com/shopperlabs/framework/releases/tag/v0.0.5
