### ISSUE TITLE
Not working in any manner

### ISSUE THREAD

**Issue by Swatinfo** [shopperlabs/framework#64]
I have tried to install this locally and on the server as well but on both of the instances, it always shows 403 forbidden.

both local and live server has Laravel 8.59.0 installed

![image](https://user-images.githubusercontent.com/75825816/132488233-78070211-73ad-4c8b-984c-18601873e686.png)

![image](https://user-images.githubusercontent.com/75825816/132487653-94010ddf-c154-4614-a14b-c397481d81e7.png)
![image](https://user-images.githubusercontent.com/75825816/132487696-3d043806-05a0-4f7f-8704-a32a0e2291fd.png)

**Comment by mckenziearts** [comment]
try to access to the login page with `shopper\login`

**Comment by Swatinfo** [comment]
Thanks, 
That does works but you should update that in documentation or redirect the /shopper to log in directly as the document is misleading for the URL to check for the after setup is completed.

**Comment by onikaii** [comment]
shopper\login  after login, 403 UNAUTHORIZED error any solution? cleared cache but 403
