### ISSUE TITLE
php artisan shopper:admin

### ISSUE THREAD

**Issue by andresilvagomez** [shopperlabs/framework#68]
When use to create the admin command

`SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "gender" violates not-null constraint`

**Comment by ryankarl65** [comment]
i have the same problem

**Comment by mckenziearts** [comment]
Can I have more details? I just tested and I did not encounter any problem. I will reopen the issue when I have more details. thank you

**Comment by ryankarl65** [comment]
![image](https://user-images.githubusercontent.com/20144355/135539901-78133136-70e1-49b5-a229-3f4dcbf9f929.png)

with the last merge, i have this error, `SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "users" does not exist`
