### ISSUE TITLE
Docs are down with error SSL_ERROR_UNRECOGNIZED_NAME_ALERT

### ISSUE THREAD

**Issue by PixellUp** [shopperlabs/framework#84]
When trying to reach [https://laravelshopper.io/documentation](https://laravelshopper.io/documentation) it redirects to to [https://docs.laravelshopper.io/](https://docs.laravelshopper.io/)

**Comment by mckenziearts** [comment]
Sorry for that But we are in the process of remaking a new site. At the end of the month it will be available again

**Comment by vlados** [comment]
Still not working
